on:
   push:
     branches:
       - master




jobs:
 build:
  runs-on: ubuntu-latest

  steps:

    - uses: actions/checkout@v3  

    - name: 'login dockerhub'
      run: docker login --username ${{secrets.username }} --password ${{secrets.password }}
    - name : "build docker image"
      run: docker build -t ${{secrets.username }}/task .
    - name : "pushing to docker hub"  
      run  :  docker push  ${{secrets.username }}/task

